local colors = {
-- content here will not be touched
-- PATCH_OPEN
Normal = {fg = "#bcbcbc", bg = "#1c1c1c"},
NvimSpacing = {link = "Normal"},
NvimTreeNormal = {link = "Normal"},
NvimTreePopup = {link = "Normal"},
Terminal = {link = "Normal"},
vimOper = {link = "Normal"},
vimParenSep = {link = "Normal"},
vimSep = {link = "Normal"},
vimVar = {link = "Normal"},
ALEError = {fg = "#1c1c1c", bg = "#d75f5f"},
ALEErrorSign = {fg = "#d75f5f"},
ALEInfo = {fg = "#d7d787"},
ALEInfoSign = {fg = "#d7d787"},
ALEVirtualTextError = {fg = "#1c1c1c", bg = "#d75f5f"},
ALEVirtualTextInfo = {fg = "#d7d787"},
ALEVirtualTextWarning = {fg = "#1c1c1c", bg = "#af87af"},
ALEWarning = {fg = "#1c1c1c", bg = "#af87af"},
ALEWarningSign = {fg = "#af87af"},
Character = {fg = "#afd7af"},
LazyReasonFt = {link = "Character"},
LazyReasonSource = {link = "Character"},
["@character"] = {link = "Character"},
CmpItemAbbrDeprecatedDefault = {fg = "#767676"},
CmpItemKindDefault = {fg = "#5f8787"},
ColorColumn = {bg = "#262626"},
Comment = {fg = "#767676"},
LazyComment = {link = "Comment"},
LspInfoTip = {link = "Comment"},
NvimTreeGitIgnored = {link = "Comment"},
TelescopeResultsComment = {link = "Comment"},
luaComment = {link = "Comment"},
vimCommentString = {link = "Comment"},
["@comment"] = {link = "Comment"},
["@text.literal"] = {link = "Comment"},
Conceal = {fg = "#767676"},
LazyDimmed = {link = "Conceal"},
LazyProp = {link = "Conceal"},
Constant = {fg = "#d7875f"},
Boolean = {link = "Constant"},
LazyProgressDone = {link = "Constant"},
LazyReasonEvent = {link = "Constant"},
Number = {link = "Constant"},
TelescopePreviewBlock = {link = "Constant"},
TelescopePreviewCharDev = {link = "Constant"},
TelescopePreviewGroup = {link = "Constant"},
TelescopePreviewPipe = {link = "Constant"},
TelescopePreviewRead = {link = "Constant"},
TelescopePreviewUser = {link = "Constant"},
TelescopeResultsConstant = {link = "Constant"},
luaConstant = {link = "Constant"},
["@constant"] = {link = "Constant"},
["@lsp.type.enumMember"] = {link = "Constant"},
CurSearch = {fg = "#1c1c1c", bg = "#afaf87"},
Cursor = {fg = "#1c1c1c", bg = "#ffaf5f"},
CursorColumn = {bg = "#303030"},
NvimTreeCursorColumn = {link = "CursorColumn"},
CursorLine = {bg = "#303030"},
LazyButton = {link = "CursorLine"},
NvimTreeCursorLine = {link = "CursorLine"},
CursorLineNr = {fg = "#ffaf5f", bold = true},
NvimTreeCursorLineNr = {link = "CursorLineNr"},
Debug = {fg = "#5f8787"},
["@debug"] = {link = "Debug"},
DevIconAi = {fg = "#cbcb41"},
DevIconAwk = {fg = "#4d5a5e"},
DevIconBabelrc = {fg = "#cbcb41"},
DevIconBash = {fg = "#89e051"},
DevIconBashProfile = {fg = "#89e051"},
DevIconBashrc = {fg = "#89e051"},
DevIconBat = {fg = "#c1f12e"},
DevIconBinaryGLTF = {fg = "#ffb13b"},
DevIconBmp = {fg = "#a074c4"},
DevIconBrewfile = {fg = "#701516"},
DevIconC = {fg = "#599eff"},
DevIconCMake = {fg = "#6d8086"},
DevIconCMakeLists = {fg = "#6d8086"},
DevIconCPlusPlus = {fg = "#f34b7d"},
DevIconClojure = {fg = "#8dc149"},
DevIconClojureC = {fg = "#8dc149"},
DevIconClojureDart = {fg = "#519aba"},
DevIconClojureJS = {fg = "#519aba"},
DevIconCobol = {fg = "#005ca5"},
DevIconCoffee = {fg = "#cbcb41"},
DevIconConf = {fg = "#6d8086"},
DevIconConfigRu = {fg = "#701516"},
DevIconConfiguration = {fg = "#ececec"},
DevIconCp = {fg = "#519aba"},
DevIconCpp = {fg = "#519aba"},
DevIconCrystal = {fg = "#c8c8c8"},
DevIconCs = {fg = "#596706"},
DevIconCsh = {fg = "#4d5a5e"},
DevIconCson = {fg = "#cbcb41"},
DevIconCss = {fg = "#42a5f5"},
DevIconCsv = {fg = "#89e051"},
DevIconCxx = {fg = "#519aba"},
DevIconD = {fg = "#427819"},
DevIconDart = {fg = "#03589c"},
DevIconDb = {fg = "#dad8d8"},
DevIconDesktopEntry = {fg = "#563d7c"},
DevIconDiff = {fg = "#41535b"},
DevIconDoc = {fg = "#185abd"},
DevIconDockerfile = {fg = "#458ee6"},
DevIconDocx = {fg = "#185abd"},
DevIconDrools = {fg = "#ffafaf"},
DevIconDropbox = {fg = "#0061fe"},
DevIconDsStore = {fg = "#41535b"},
DevIconDump = {fg = "#dad8d8"},
DevIconEdn = {fg = "#519aba"},
DevIconEex = {fg = "#a074c4"},
DevIconEjs = {fg = "#cbcb41"},
DevIconElm = {fg = "#519aba"},
DevIconEnv = {fg = "#faf743"},
DevIconEpp = {fg = "#ffa61a"},
DevIconErb = {fg = "#701516"},
DevIconErl = {fg = "#b83998"},
DevIconEslintrc = {fg = "#4b32c3"},
DevIconEx = {fg = "#a074c4"},
DevIconExs = {fg = "#a074c4"},
DevIconFavicon = {fg = "#cbcb41"},
DevIconFennel = {fg = "#fff3d7"},
DevIconFish = {fg = "#4d5a5e"},
DevIconFs = {fg = "#519aba"},
DevIconFsharp = {fg = "#519aba"},
DevIconFsi = {fg = "#519aba"},
DevIconFsscript = {fg = "#519aba"},
DevIconFsx = {fg = "#519aba"},
DevIconGDScript = {fg = "#6d8086"},
DevIconGemfile = {fg = "#701516"},
DevIconGemspec = {fg = "#701516"},
DevIconGif = {fg = "#a074c4"},
DevIconGitAttributes = {fg = "#41535b"},
DevIconGitCommit = {fg = "#41535b"},
DevIconGitConfig = {fg = "#41535b"},
DevIconGitIgnore = {fg = "#41535b"},
DevIconGitLogo = {fg = "#f14c28"},
DevIconGitModules = {fg = "#41535b"},
DevIconGitlabCI = {fg = "#e24329"},
DevIconGo = {fg = "#519aba"},
DevIconGodotProject = {fg = "#6d8086"},
DevIconGraphQL = {fg = "#e535ab"},
DevIconGruntfile = {fg = "#e37933"},
DevIconGulpfile = {fg = "#cc3e44"},
DevIconGvimrc = {fg = "#019833"},
DevIconH = {fg = "#a074c4"},
DevIconHaml = {fg = "#eaeae1"},
DevIconHbs = {fg = "#f0772b"},
DevIconHeex = {fg = "#a074c4"},
DevIconHh = {fg = "#a074c4"},
DevIconHpp = {fg = "#a074c4"},
DevIconHrl = {fg = "#b83998"},
DevIconHs = {fg = "#a074c4"},
DevIconHtm = {fg = "#e34c26"},
DevIconHtml = {fg = "#e44d26"},
DevIconHxx = {fg = "#a074c4"},
DevIconIco = {fg = "#cbcb41"},
DevIconImportConfiguration = {fg = "#ececec"},
DevIconIni = {fg = "#6d8086"},
DevIconJava = {fg = "#cc3e44"},
DevIconJavaScriptReactSpec = {fg = "#20c2e3"},
DevIconJavaScriptReactTest = {fg = "#20c2e3"},
DevIconJl = {fg = "#a270ba"},
DevIconJpeg = {fg = "#a074c4"},
DevIconJpg = {fg = "#a074c4"},
DevIconJs = {fg = "#cbcb41"},
DevIconJson = {fg = "#cbcb41"},
DevIconJson5 = {fg = "#cbcb41"},
DevIconJsx = {fg = "#20c2e3"},
DevIconKotlin = {fg = "#7f52ff"},
DevIconKotlinScript = {fg = "#7f52ff"},
DevIconKsh = {fg = "#4d5a5e"},
DevIconLeex = {fg = "#a074c4"},
DevIconLess = {fg = "#563d7c"},
DevIconLhs = {fg = "#a074c4"},
DevIconLicense = {fg = "#cbcb41"},
DevIconLiquid = {fg = "#95bf47"},
DevIconLock = {fg = "#bbbbbb"},
DevIconLog = {fg = "#ffffff"},
DevIconLua = {fg = "#51a0cf"},
DevIconLuau = {fg = "#51a0cf"},
DevIconMakefile = {fg = "#6d8086"},
DevIconMarkdown = {fg = "#519aba"},
DevIconMaterial = {fg = "#b83998"},
DevIconMd = {fg = "#ffffff"},
DevIconMdx = {fg = "#519aba"},
DevIconMint = {fg = "#87c095"},
DevIconMixLock = {fg = "#a074c4"},
DevIconMjs = {fg = "#f1e05a"},
DevIconMl = {fg = "#e37933"},
DevIconMli = {fg = "#e37933"},
DevIconMotoko = {fg = "#9772fb"},
DevIconMustache = {fg = "#e37933"},
DevIconNPMIgnore = {fg = "#e8274b"},
DevIconNPMrc = {fg = "#e8274b"},
DevIconNim = {fg = "#f3d400"},
DevIconNix = {fg = "#7ebae4"},
DevIconNodeModules = {fg = "#e8274b"},
DevIconOPUS = {fg = "#f88a02"},
DevIconOpenTypeFont = {fg = "#ececec"},
DevIconOrgMode = {fg = "#77aa99"},
DevIconPackageJson = {fg = "#e8274b"},
DevIconPackageLockJson = {fg = "#7a0d21"},
DevIconPackedResource = {fg = "#6d8086"},
DevIconPdf = {fg = "#b30b00"},
DevIconPhp = {fg = "#a074c4"},
DevIconPl = {fg = "#519aba"},
DevIconPm = {fg = "#519aba"},
DevIconPng = {fg = "#a074c4"},
DevIconPp = {fg = "#ffa61a"},
DevIconPpt = {fg = "#cb4a32"},
DevIconPrisma = {fg = "#ffffff"},
DevIconProcfile = {fg = "#a074c4"},
DevIconProlog = {fg = "#e4b854"},
DevIconPsManifestfile = {fg = "#6975c4"},
DevIconPsScriptModulefile = {fg = "#6975c4"},
DevIconPsScriptfile = {fg = "#4273ca"},
DevIconPsb = {fg = "#519aba"},
DevIconPsd = {fg = "#519aba"},
DevIconPy = {fg = "#ffbc03"},
DevIconPyc = {fg = "#ffe291"},
DevIconPyd = {fg = "#ffe291"},
DevIconPyo = {fg = "#ffe291"},
DevIconQuery = {fg = "#90a850"},
DevIconR = {fg = "#358a5b"},
DevIconRake = {fg = "#701516"},
DevIconRakefile = {fg = "#701516"},
DevIconRb = {fg = "#701516"},
DevIconRlib = {fg = "#dea584"},
DevIconRmd = {fg = "#519aba"},
DevIconRproj = {fg = "#358a5b"},
DevIconRs = {fg = "#dea584"},
DevIconRss = {fg = "#fb9d3b"},
DevIconSass = {fg = "#f55385"},
DevIconScala = {fg = "#cc3e44"},
DevIconScheme = {fg = "#000000"},
DevIconScss = {fg = "#f55385"},
DevIconSettingsJson = {fg = "#854cc7"},
DevIconSh = {fg = "#4d5a5e"},
DevIconSig = {fg = "#e37933"},
DevIconSlim = {fg = "#e34c26"},
DevIconSln = {fg = "#854cc7"},
DevIconSml = {fg = "#e37933"},
DevIconSolidity = {fg = "#519aba"},
DevIconSpecJs = {fg = "#cbcb41"},
DevIconSpecTs = {fg = "#519aba"},
DevIconSql = {fg = "#dad8d8"},
DevIconStyl = {fg = "#8dc149"},
DevIconSuo = {fg = "#854cc7"},
DevIconSvelte = {fg = "#ff3e00"},
DevIconSvg = {fg = "#ffb13b"},
DevIconSwift = {fg = "#e37933"},
DevIconSystemVerilog = {fg = "#019833"},
DevIconTFVars = {fg = "#5f43e9"},
DevIconTcl = {fg = "#1e5cb3"},
DevIconTerminal = {fg = "#31b53e"},
DevIconTerraform = {fg = "#5f43e9"},
DevIconTestJs = {fg = "#cbcb41"},
DevIconTestTs = {fg = "#519aba"},
DevIconTex = {fg = "#3d6117"},
DevIconTextResource = {fg = "#cbcb41"},
DevIconTextScene = {fg = "#a074c4"},
DevIconToml = {fg = "#6d8086"},
DevIconTor = {fg = "#519aba"},
DevIconTs = {fg = "#519aba"},
DevIconTsx = {fg = "#1354bf"},
DevIconTwig = {fg = "#8dc149"},
DevIconTxt = {fg = "#89e051"},
DevIconTypeScriptReactSpec = {fg = "#1354bf"},
DevIconTypeScriptReactTest = {fg = "#1354bf"},
DevIconVHDL = {fg = "#019833"},
DevIconVagrantfile = {fg = "#1563ff"},
DevIconVala = {fg = "#7239b3"},
DevIconVerilog = {fg = "#019833"},
DevIconVim = {fg = "#019833"},
DevIconVimrc = {fg = "#019833"},
DevIconVue = {fg = "#8dc149"},
DevIconWasm = {fg = "#5c4cdb"},
DevIconWebmanifest = {fg = "#f1e05a"},
DevIconWebp = {fg = "#a074c4"},
DevIconWebpack = {fg = "#519aba"},
DevIconXcPlayground = {fg = "#e37933"},
DevIconXls = {fg = "#207245"},
DevIconXlsx = {fg = "#207245"},
DevIconXml = {fg = "#e37933"},
DevIconXul = {fg = "#e37933"},
DevIconYaml = {fg = "#6d8086"},
DevIconYml = {fg = "#6d8086"},
DevIconZig = {fg = "#f69a1b"},
DevIconZsh = {fg = "#89e051"},
DevIconZshenv = {fg = "#89e051"},
DevIconZshprofile = {fg = "#89e051"},
DevIconZshrc = {fg = "#89e051"},
DevIconsbt = {fg = "#cc3e44"},
DiagnosticError = {fg = "red"},
DiagnosticFloatingError = {link = "DiagnosticError"},
DiagnosticSignError = {link = "DiagnosticError"},
DiagnosticVirtualTextError = {link = "DiagnosticError"},
NvimTreeLspDiagnosticsError = {link = "DiagnosticError"},
DiagnosticHint = {fg = "lightgrey"},
DiagnosticFloatingHint = {link = "DiagnosticHint"},
DiagnosticSignHint = {link = "DiagnosticHint"},
DiagnosticVirtualTextHint = {link = "DiagnosticHint"},
NvimTreeLspDiagnosticsHint = {link = "DiagnosticHint"},
DiagnosticInfo = {fg = "lightblue"},
DiagnosticFloatingInfo = {link = "DiagnosticInfo"},
DiagnosticSignInfo = {link = "DiagnosticInfo"},
DiagnosticVirtualTextInfo = {link = "DiagnosticInfo"},
NvimTreeLspDiagnosticsInformation = {link = "DiagnosticInfo"},
DiagnosticOk = {fg = "lightgreen"},
DiagnosticFloatingOk = {link = "DiagnosticOk"},
DiagnosticSignOk = {link = "DiagnosticOk"},
DiagnosticVirtualTextOk = {link = "DiagnosticOk"},
DiagnosticUnderlineError = {sp = "red", underline = true},
DiagnosticUnderlineHint = {sp = "lightgrey", underline = true},
DiagnosticUnderlineInfo = {sp = "lightblue", underline = true},
DiagnosticUnderlineOk = {sp = "lightgreen", underline = true},
DiagnosticUnderlineWarn = {sp = "orange", underline = true},
DiagnosticWarn = {fg = "orange"},
DiagnosticFloatingWarn = {link = "DiagnosticWarn"},
DiagnosticSignWarn = {link = "DiagnosticWarn"},
DiagnosticVirtualTextWarn = {link = "DiagnosticWarn"},
LazyNoCond = {link = "DiagnosticWarn"},
NvimTreeLspDiagnosticsWarning = {link = "DiagnosticWarn"},
DiffAdd = {fg = "#000000", bg = "#87af87"},
GitSignsAddLn = {link = "DiffAdd"},
GitSignsAddPreview = {link = "DiffAdd"},
TelescopeResultsDiffAdd = {link = "DiffAdd"},
DiffChange = {fg = "#000000", bg = "#afafaf"},
GitSignsChange = {link = "DiffChange"},
GitSignsChangeLn = {link = "DiffChange"},
TelescopeResultsDiffChange = {link = "DiffChange"},
DiffDelete = {fg = "#af875f"},
GitSignsDeletePreview = {link = "DiffDelete"},
GitSignsDeleteVirtLn = {link = "DiffDelete"},
TelescopeResultsDiffDelete = {link = "DiffDelete"},
DiffText = {fg = "#000000", bg = "#d7d7d7"},
Directory = {fg = "#87afaf", bold = true},
NvimTreeEmptyFolderName = {link = "Directory"},
NvimTreeFolderName = {link = "Directory"},
NvimTreeOpenedFolderName = {link = "Directory"},
TelescopePreviewDate = {link = "Directory"},
TelescopePreviewDirectory = {link = "Directory"},
EndOfBuffer = {fg = "#585858"},
NvimTreeEndOfBuffer = {link = "EndOfBuffer"},
Error = {fg = "#d75f5f", bg = "#1c1c1c", reverse = true},
NvimInvalid = {link = "Error"},
luaError = {link = "Error"},
luaParenError = {link = "Error"},
ErrorMsg = {fg = "#d75f5f", bg = "#1c1c1c", reverse = true},
LazyTaskError = {link = "ErrorMsg"},
NvimInvalidSpacing = {link = "ErrorMsg"},
FloatBorder = {fg = "#767676", bg = "#262626"},
FloatShadow = {bg = "black", blend = 80},
FloatShadowThrough = {bg = "black", blend = 100},
FoldColumn = {fg = "#585858"},
CursorLineFold = {link = "FoldColumn"},
Folded = {fg = "#9e9e9e", bg = "#262626"},
GitSignsStagedAdd = {fg = "#435743"},
GitSignsStagedAddLn = {fg = "#000000", bg = "#87af87"},
GitSignsStagedAddNr = {fg = "#435743"},
GitSignsStagedChange = {fg = "#000000", bg = "#afafaf"},
GitSignsStagedChangeLn = {fg = "#000000", bg = "#afafaf"},
GitSignsStagedChangeNr = {fg = "#000000", bg = "#afafaf"},
GitSignsStagedChangedelete = {fg = "#000000", bg = "#afafaf"},
GitSignsStagedChangedeleteLn = {fg = "#000000", bg = "#afafaf"},
GitSignsStagedChangedeleteNr = {fg = "#000000", bg = "#afafaf"},
GitSignsStagedDelete = {fg = "#6b2f2f"},
GitSignsStagedDeleteNr = {fg = "#6b2f2f"},
GitSignsStagedTopdelete = {fg = "#6b2f2f"},
GitSignsStagedTopdeleteNr = {fg = "#6b2f2f"},
Identifier = {fg = "#87afaf"},
Function = {link = "Identifier"},
LazyReasonImport = {link = "Identifier"},
NvimIdentifier = {link = "Identifier"},
TelescopeMultiIcon = {link = "Identifier"},
TelescopeResultsIdentifier = {link = "Identifier"},
luaFunc = {link = "Identifier"},
["@field"] = {link = "Identifier"},
["@lsp.type.parameter"] = {link = "Identifier"},
["@lsp.type.property"] = {link = "Identifier"},
["@lsp.type.variable"] = {link = "Identifier"},
["@namespace"] = {link = "Identifier"},
["@parameter"] = {link = "Identifier"},
["@property"] = {link = "Identifier"},
["@text.reference"] = {link = "Identifier"},
["@variable"] = {link = "Identifier"},
IncSearch = {fg = "#1c1c1c", bg = "#ffaf5f"},
LazyH1 = {link = "IncSearch"},
LineNr = {fg = "#585858"},
LazyProgressTodo = {link = "LineNr"},
NvimTreeLineNr = {link = "LineNr"},
TelescopeResultsLineNr = {link = "LineNr"},
LineNrAbove = {fg = "#585858"},
LineNrBelow = {fg = "#585858"},
MatchParen = {fg = "#5f8787", bg = "#1c1c1c", reverse = true},
ModeMsg = {fg = "#1c1c1c", bg = "#d7d787"},
MoreMsg = {fg = "#87af87"},
NonText = {fg = "#585858"},
GitSignsCurrentLineBlame = {link = "NonText"},
TelescopePreviewHyphen = {link = "NonText"},
TelescopePromptCounter = {link = "NonText"},
TelescopeResultsDiffUntracked = {link = "NonText"},
Whitespace = {link = "NonText"},
NvimInternalError = {fg = "red", bg = "red"},
NvimFigureBrace = {link = "NvimInternalError"},
NvimInvalidSingleQuotedUnknownEscape = {link = "NvimInternalError"},
NvimSingleQuotedUnknownEscape = {link = "NvimInternalError"},
NvimTreeBookmark = {fg = "#87af87"},
NvimTreeExecFile = {fg = "#87af87", bold = true},
NvimTreeFolderIcon = {fg = "#8094b4"},
NvimTreeClosedFolderIcon = {link = "NvimTreeFolderIcon"},
NvimTreeOpenedFolderIcon = {link = "NvimTreeFolderIcon"},
NvimTreeGitDeleted = {fg = "#d7875f"},
NvimTreeFileDeleted = {link = "NvimTreeGitDeleted"},
NvimTreeGitDirty = {fg = "#d7875f"},
NvimTreeFileDirty = {link = "NvimTreeGitDirty"},
NvimTreeGitMerge = {fg = "#d7d787"},
NvimTreeFileMerge = {link = "NvimTreeGitMerge"},
NvimTreeGitNew = {fg = "#afaf87"},
NvimTreeFileNew = {link = "NvimTreeGitNew"},
NvimTreeGitRenamed = {fg = "#af87af"},
NvimTreeFileRenamed = {link = "NvimTreeGitRenamed"},
NvimTreeGitStaged = {fg = "#87af87"},
NvimTreeFileStaged = {link = "NvimTreeGitStaged"},
NvimTreeImageFile = {fg = "#af87af", bold = true},
NvimTreeIndentMarker = {fg = "#8094b4"},
NvimTreeLiveFilterPrefix = {fg = "#af87af", bold = true},
NvimTreeLiveFilterValue = {bold = true},
NvimTreeModifiedFile = {fg = "#87af87"},
NvimTreeOpenedFile = {fg = "#87af87", bold = true},
NvimTreeRootFolder = {fg = "#af87af"},
NvimTreeSpecialFile = {fg = "#afaf87", bold = true, underline = true},
NvimTreeSymlink = {fg = "#5f8787", bold = true},
NvimTreeWindowPicker = {fg = "#ededed", bg = "#4493c8", bold = true},
Pmenu = {bg = "#262626"},
MessageWindow = {link = "Pmenu"},
NormalFloat = {link = "Pmenu"},
PmenuExtra = {link = "Pmenu"},
PmenuKind = {link = "Pmenu"},
PmenuSel = {fg = "#1c1c1c", bg = "#afaf87"},
PmenuExtraSel = {link = "PmenuSel"},
PmenuKindSel = {link = "PmenuSel"},
PmenuThumb = {bg = "#767676"},
PreProc = {fg = "#afaf87"},
Define = {link = "PreProc"},
Include = {link = "PreProc"},
Macro = {link = "PreProc"},
PreCondit = {link = "PreProc"},
elixirAtom = {link = "PreProc"},
["@preproc"] = {link = "PreProc"},
Question = {fg = "#afaf87"},
QuickFixLine = {fg = "#1c1c1c", bg = "#5f87af"},
RedrawDebugClear = {bg = "yellow"},
RedrawDebugComposed = {bg = "green"},
RedrawDebugNormal = {reverse = true},
RedrawDebugRecompose = {bg = "red"},
Search = {fg = "#1c1c1c", bg = "#87af87"},
Substitute = {link = "Search"},
TelescopePreviewMatch = {link = "Search"},
SignColumn = {fg = "None", bg = "None"},
Special = {fg = "#5f8787"},
Delimiter = {link = "Special"},
LazyReasonPlugin = {link = "Special"},
SpecialChar = {link = "Special"},
SpecialComment = {link = "Special"},
Tag = {link = "Special"},
TelescopePreviewLink = {link = "Special"},
["@constructor"] = {link = "Special"},
SpecialKey = {fg = "#585858"},
SpellBad = {sp = "#d75f5f", undercurl = true},
SpellCap = {sp = "#5f87af", undercurl = true},
SpellLocal = {sp = "#87af87", undercurl = true},
SpellRare = {sp = "#d7afd7", undercurl = true},
Statement = {fg = "#af87af"},
Conditional = {link = "Statement"},
Exception = {link = "Statement"},
Keyword = {link = "Statement"},
Label = {link = "Statement"},
LazyReasonKeys = {link = "Statement"},
Operator = {link = "Statement"},
Repeat = {link = "Statement"},
TelescopePreviewSocket = {link = "Statement"},
TelescopePreviewWrite = {link = "Statement"},
elixirBlockDefinition = {link = "Statement"},
elixirCallbackDefine = {link = "Statement"},
elixirDefine = {link = "Statement"},
elixirDelegateDefine = {link = "Statement"},
elixirExUnitMacro = {link = "Statement"},
elixirExceptionDefine = {link = "Statement"},
elixirGuard = {link = "Statement"},
elixirImplDefine = {link = "Statement"},
elixirInclude = {link = "Statement"},
elixirKeyword = {link = "Statement"},
elixirMacroDefine = {link = "Statement"},
elixirModuleDefine = {link = "Statement"},
elixirOperator = {link = "Statement"},
elixirOverridableDefine = {link = "Statement"},
elixirPrivateDefine = {link = "Statement"},
elixirPrivateGuard = {link = "Statement"},
elixirPrivateMacroDefine = {link = "Statement"},
elixirPrivateRecordDefine = {link = "Statement"},
elixirProtocolDefine = {link = "Statement"},
elixirRecordDefine = {link = "Statement"},
elixirStructDefine = {link = "Statement"},
javaScriptFunction = {link = "Statement"},
javaScriptIdentifier = {link = "Statement"},
luaStatement = {link = "Statement"},
rubyDefine = {link = "Statement"},
rubyMacro = {link = "Statement"},
sqlKeyword = {link = "Statement"},
yamlBlockMappingKey = {link = "Statement"},
StatusLine = {fg = "#1c1c1c", bg = "#9e9e9e"},
MsgSeparator = {link = "StatusLine"},
NvimTreeStatusLine = {link = "StatusLine"},
StatusLineTerm = {link = "StatusLine"},
StatusLineNC = {fg = "#1c1c1c", bg = "#767676"},
NvimTreeStatusLineNC = {link = "StatusLineNC"},
StatusLineTermNC = {link = "StatusLineNC"},
String = {fg = "#87af87"},
NvimString = {link = "String"},
TelescopePreviewExecute = {link = "String"},
TelescopePreviewSize = {link = "String"},
elixirDocTest = {link = "String"},
luaString = {link = "String"},
luaString2 = {link = "String"},
markdownUrl = {link = "String"},
["@string"] = {link = "String"},
TabLine = {fg = "#1c1c1c", bg = "#767676"},
TabLineFill = {fg = "#1c1c1c", bg = "#767676"},
TabLineSel = {bold = true},
TermCursor = {reverse = true},
GitSignsAddInline = {link = "TermCursor"},
GitSignsChangeInline = {link = "TermCursor"},
GitSignsDeleteInline = {link = "TermCursor"},
Title = {fg = "#d7d787", bold = true},
FloatTitle = {link = "Title"},
LazyCommitType = {link = "Title"},
LspInfoTitle = {link = "Title"},
NullLsInfoSources = {link = "Title"},
gitCommitSummary = {link = "Title"},
Todo = {fg = "#d7d787", bg = "#1c1c1c", reverse = true},
PopupNotification = {link = "Todo"},
luaTodo = {link = "Todo"},
["@text.todo"] = {link = "Todo"},
ToolbarButton = {fg = "#9e9e9e", bg = "#1c1c1c", bold = true, reverse = true},
Type = {fg = "#87afd7"},
LspInfoFiletype = {link = "Type"},
NullLsInfoTitle = {link = "Type"},
NvimNumberPrefix = {link = "Type"},
NvimOptionSigil = {link = "Type"},
StorageClass = {link = "Type"},
Structure = {link = "Type"},
TelescopeMultiSelection = {link = "Type"},
Typedef = {link = "Type"},
["@lsp.type.type"] = {link = "Type"},
["@type"] = {link = "Type"},
Underlined = {underline = true},
VertSplit = {fg = "#767676"},
WinSeparator = {link = "VertSplit"},
Visual = {fg = "#1c1c1c", bg = "#87afaf"},
LazyButtonActive = {link = "Visual"},
TelescopePreviewLine = {link = "Visual"},
VisualNOS = {fg = "#1c1c1c", bg = "#5f8787"},
WarningMsg = {fg = "#d7875f"},
WildMenu = {fg = "#1c1c1c", bg = "#d7d787"},
WinBar = {bold = true},
WinBarNC = {link = "WinBar"},
["colorizer_mb_000000"] = {fg = "white", bg = "#000000"},
["colorizer_mb_005ca5"] = {fg = "white", bg = "#005ca5"},
["colorizer_mb_0061fe"] = {fg = "white", bg = "#0061fe"},
["colorizer_mb_008000"] = {fg = "white", bg = "#008000"},
["colorizer_mb_019833"] = {fg = "white", bg = "#019833"},
["colorizer_mb_03589c"] = {fg = "white", bg = "#03589c"},
["colorizer_mb_1354bf"] = {fg = "white", bg = "#1354bf"},
["colorizer_mb_1563ff"] = {fg = "white", bg = "#1563ff"},
["colorizer_mb_185abd"] = {fg = "white", bg = "#185abd"},
["colorizer_mb_191724"] = {fg = "white", bg = "#191724"},
["colorizer_mb_1c1c1c"] = {fg = "white", bg = "#1c1c1c"},
["colorizer_mb_1e5cb3"] = {fg = "white", bg = "#1e5cb3"},
["colorizer_mb_207245"] = {fg = "white", bg = "#207245"},
["colorizer_mb_20c2e3"] = {fg = "black", bg = "#20c2e3"},
["colorizer_mb_262626"] = {fg = "white", bg = "#262626"},
["colorizer_mb_303030"] = {fg = "white", bg = "#303030"},
["colorizer_mb_31748f"] = {fg = "white", bg = "#31748f"},
["colorizer_mb_31b53e"] = {fg = "black", bg = "#31b53e"},
["colorizer_mb_358a5b"] = {fg = "white", bg = "#358a5b"},
["colorizer_mb_3d6117"] = {fg = "white", bg = "#3d6117"},
["colorizer_mb_41535b"] = {fg = "white", bg = "#41535b"},
["colorizer_mb_4273ca"] = {fg = "white", bg = "#4273ca"},
["colorizer_mb_427819"] = {fg = "white", bg = "#427819"},
["colorizer_mb_42a5f5"] = {fg = "black", bg = "#42a5f5"},
["colorizer_mb_435743"] = {fg = "white", bg = "#435743"},
["colorizer_mb_4493c8"] = {fg = "black", bg = "#4493c8"},
["colorizer_mb_458ee6"] = {fg = "black", bg = "#458ee6"},
["colorizer_mb_4b32c3"] = {fg = "white", bg = "#4b32c3"},
["colorizer_mb_4d5a5e"] = {fg = "white", bg = "#4d5a5e"},
["colorizer_mb_519aba"] = {fg = "black", bg = "#519aba"},
["colorizer_mb_51a0cf"] = {fg = "black", bg = "#51a0cf"},
["colorizer_mb_563d7c"] = {fg = "white", bg = "#563d7c"},
["colorizer_mb_585858"] = {fg = "white", bg = "#585858"},
["colorizer_mb_596706"] = {fg = "white", bg = "#596706"},
["colorizer_mb_599eff"] = {fg = "black", bg = "#599eff"},
["colorizer_mb_5c4cdb"] = {fg = "white", bg = "#5c4cdb"},
["colorizer_mb_5f43e9"] = {fg = "white", bg = "#5f43e9"},
["colorizer_mb_5f8787"] = {fg = "white", bg = "#5f8787"},
["colorizer_mb_5f87af"] = {fg = "black", bg = "#5f87af"},
["colorizer_mb_5fff00"] = {fg = "black", bg = "#5fff00"},
["colorizer_mb_6975c4"] = {fg = "white", bg = "#6975c4"},
["colorizer_mb_6b2f2f"] = {fg = "white", bg = "#6b2f2f"},
["colorizer_mb_6d8086"] = {fg = "white", bg = "#6d8086"},
["colorizer_mb_701516"] = {fg = "white", bg = "#701516"},
["colorizer_mb_7239b3"] = {fg = "white", bg = "#7239b3"},
["colorizer_mb_767676"] = {fg = "white", bg = "#767676"},
["colorizer_mb_77aa99"] = {fg = "black", bg = "#77aa99"},
["colorizer_mb_7a0d21"] = {fg = "white", bg = "#7a0d21"},
["colorizer_mb_7ebae4"] = {fg = "black", bg = "#7ebae4"},
["colorizer_mb_7f52ff"] = {fg = "white", bg = "#7f52ff"},
["colorizer_mb_8094b4"] = {fg = "black", bg = "#8094b4"},
["colorizer_mb_854cc7"] = {fg = "white", bg = "#854cc7"},
["colorizer_mb_87af87"] = {fg = "black", bg = "#87af87"},
["colorizer_mb_87afaf"] = {fg = "black", bg = "#87afaf"},
["colorizer_mb_87afd7"] = {fg = "black", bg = "#87afd7"},
["colorizer_mb_87c095"] = {fg = "black", bg = "#87c095"},
["colorizer_mb_89e051"] = {fg = "black", bg = "#89e051"},
["colorizer_mb_8dc149"] = {fg = "black", bg = "#8dc149"},
["colorizer_mb_90a850"] = {fg = "black", bg = "#90a850"},
["colorizer_mb_90ee90"] = {fg = "black", bg = "#90ee90"},
["colorizer_mb_95bf47"] = {fg = "black", bg = "#95bf47"},
["colorizer_mb_9772fb"] = {fg = "black", bg = "#9772fb"},
["colorizer_mb_9ccfd8"] = {fg = "black", bg = "#9ccfd8"},
["colorizer_mb_9e9e9e"] = {fg = "black", bg = "#9e9e9e"},
["colorizer_mb_a074c4"] = {fg = "black", bg = "#a074c4"},
["colorizer_mb_a270ba"] = {fg = "black", bg = "#a270ba"},
["colorizer_mb_add8e6"] = {fg = "black", bg = "#add8e6"},
["colorizer_mb_af875f"] = {fg = "black", bg = "#af875f"},
["colorizer_mb_af87af"] = {fg = "black", bg = "#af87af"},
["colorizer_mb_afaf87"] = {fg = "black", bg = "#afaf87"},
["colorizer_mb_afafaf"] = {fg = "black", bg = "#afafaf"},
["colorizer_mb_afd7af"] = {fg = "black", bg = "#afd7af"},
["colorizer_mb_b30b00"] = {fg = "white", bg = "#b30b00"},
["colorizer_mb_b83998"] = {fg = "white", bg = "#b83998"},
["colorizer_mb_bbbbbb"] = {fg = "black", bg = "#bbbbbb"},
["colorizer_mb_bcbcbc"] = {fg = "black", bg = "#bcbcbc"},
["colorizer_mb_c1f12e"] = {fg = "black", bg = "#c1f12e"},
["colorizer_mb_c4a7e7"] = {fg = "black", bg = "#c4a7e7"},
["colorizer_mb_c8c8c8"] = {fg = "black", bg = "#c8c8c8"},
["colorizer_mb_cb4a32"] = {fg = "white", bg = "#cb4a32"},
["colorizer_mb_cbcb41"] = {fg = "black", bg = "#cbcb41"},
["colorizer_mb_cc3e44"] = {fg = "white", bg = "#cc3e44"},
["colorizer_mb_d3d3d3"] = {fg = "black", bg = "#d3d3d3"},
["colorizer_mb_d75f5f"] = {fg = "black", bg = "#d75f5f"},
["colorizer_mb_d7875f"] = {fg = "black", bg = "#d7875f"},
["colorizer_mb_d7afd7"] = {fg = "black", bg = "#d7afd7"},
["colorizer_mb_d7d787"] = {fg = "black", bg = "#d7d787"},
["colorizer_mb_d7d7d7"] = {fg = "black", bg = "#d7d7d7"},
["colorizer_mb_dad8d8"] = {fg = "black", bg = "#dad8d8"},
["colorizer_mb_dea584"] = {fg = "black", bg = "#dea584"},
["colorizer_mb_e0def4"] = {fg = "black", bg = "#e0def4"},
["colorizer_mb_e24329"] = {fg = "white", bg = "#e24329"},
["colorizer_mb_e34c26"] = {fg = "white", bg = "#e34c26"},
["colorizer_mb_e37933"] = {fg = "black", bg = "#e37933"},
["colorizer_mb_e44d26"] = {fg = "white", bg = "#e44d26"},
["colorizer_mb_e4b854"] = {fg = "black", bg = "#e4b854"},
["colorizer_mb_e535ab"] = {fg = "white", bg = "#e535ab"},
["colorizer_mb_e8274b"] = {fg = "white", bg = "#e8274b"},
["colorizer_mb_eaeae1"] = {fg = "black", bg = "#eaeae1"},
["colorizer_mb_eb6f92"] = {fg = "black", bg = "#eb6f92"},
["colorizer_mb_ebbcba"] = {fg = "black", bg = "#ebbcba"},
["colorizer_mb_ececec"] = {fg = "black", bg = "#ececec"},
["colorizer_mb_ededed"] = {fg = "black", bg = "#ededed"},
["colorizer_mb_f0772b"] = {fg = "black", bg = "#f0772b"},
["colorizer_mb_f14c28"] = {fg = "white", bg = "#f14c28"},
["colorizer_mb_f1e05a"] = {fg = "black", bg = "#f1e05a"},
["colorizer_mb_f34b7d"] = {fg = "black", bg = "#f34b7d"},
["colorizer_mb_f3d400"] = {fg = "black", bg = "#f3d400"},
["colorizer_mb_f55385"] = {fg = "black", bg = "#f55385"},
["colorizer_mb_f69a1b"] = {fg = "black", bg = "#f69a1b"},
["colorizer_mb_f6c177"] = {fg = "black", bg = "#f6c177"},
["colorizer_mb_f88a02"] = {fg = "black", bg = "#f88a02"},
["colorizer_mb_faf743"] = {fg = "black", bg = "#faf743"},
["colorizer_mb_fb9d3b"] = {fg = "black", bg = "#fb9d3b"},
["colorizer_mb_ff0000"] = {fg = "white", bg = "#ff0000"},
["colorizer_mb_ff3e00"] = {fg = "white", bg = "#ff3e00"},
["colorizer_mb_ffa500"] = {fg = "black", bg = "#ffa500"},
["colorizer_mb_ffa61a"] = {fg = "black", bg = "#ffa61a"},
["colorizer_mb_ffaf5f"] = {fg = "black", bg = "#ffaf5f"},
["colorizer_mb_ffafaf"] = {fg = "black", bg = "#ffafaf"},
["colorizer_mb_ffb13b"] = {fg = "black", bg = "#ffb13b"},
["colorizer_mb_ffbc03"] = {fg = "black", bg = "#ffbc03"},
["colorizer_mb_ffe291"] = {fg = "black", bg = "#ffe291"},
["colorizer_mb_fff3d7"] = {fg = "black", bg = "#fff3d7"},
["colorizer_mb_ffff00"] = {fg = "black", bg = "#ffff00"},
["colorizer_mb_ffffff"] = {fg = "black", bg = "#ffffff"},
debugBreakpoint = {fg = "#1c1c1c", bg = "#d7875f"},
debugPC = {fg = "#1c1c1c", bg = "#5f87af"},
diffAdded = {fg = "#87af87"},
GitSignsAdd = {link = "diffAdded"},
diffRemoved = {fg = "#d75f5f"},
GitSignsDelete = {link = "diffRemoved"},
diffSubname = {fg = "#af87af"},
lCursor = {fg = "#1c1c1c", bg = "#5fff00"},
["lualine_c_2_command"] = {fg = "#c4a7e7", bg = "#191724"},
["lualine_c_2_inactive"] = {fg = "#eb6f92", bg = "#191724"},
["lualine_c_2_insert"] = {fg = "#eb6f92", bg = "#191724"},
["lualine_c_2_normal"] = {fg = "#eb6f92", bg = "#191724"},
["lualine_c_2_replace"] = {fg = "#eb6f92", bg = "#191724"},
["lualine_c_2_terminal"] = {fg = "#eb6f92", bg = "#191724"},
["lualine_c_2_visual"] = {fg = "#eb6f92", bg = "#191724"},
["lualine_c_branch_command"] = {fg = "#ebbcba", bg = "#191724", bold = true},
["lualine_c_branch_inactive"] = {fg = "#ebbcba", bg = "#191724", bold = true},
["lualine_c_branch_insert"] = {fg = "#ebbcba", bg = "#191724", bold = true},
["lualine_c_branch_normal"] = {fg = "#ebbcba", bg = "#191724", bold = true},
["lualine_c_branch_replace"] = {fg = "#ebbcba", bg = "#191724", bold = true},
["lualine_c_branch_terminal"] = {fg = "#ebbcba", bg = "#191724", bold = true},
["lualine_c_branch_visual"] = {fg = "#ebbcba", bg = "#191724", bold = true},
["lualine_c_diff_added_command"] = {fg = "#31748f", bg = "#191724"},
["lualine_c_diff_added_inactive"] = {fg = "#31748f", bg = "#191724"},
["lualine_c_diff_added_insert"] = {fg = "#31748f", bg = "#191724"},
["lualine_c_diff_added_normal"] = {fg = "#31748f", bg = "#191724"},
["lualine_c_diff_added_replace"] = {fg = "#31748f", bg = "#191724"},
["lualine_c_diff_added_terminal"] = {fg = "#31748f", bg = "#191724"},
["lualine_c_diff_added_visual"] = {fg = "#31748f", bg = "#191724"},
["lualine_c_diff_modified_command"] = {fg = "#f6c177", bg = "#191724"},
["lualine_c_diff_modified_inactive"] = {fg = "#f6c177", bg = "#191724"},
["lualine_c_diff_modified_insert"] = {fg = "#f6c177", bg = "#191724"},
["lualine_c_diff_modified_normal"] = {fg = "#f6c177", bg = "#191724"},
["lualine_c_diff_modified_replace"] = {fg = "#f6c177", bg = "#191724"},
["lualine_c_diff_modified_terminal"] = {fg = "#f6c177", bg = "#191724"},
["lualine_c_diff_modified_visual"] = {fg = "#f6c177", bg = "#191724"},
["lualine_c_diff_removed_command"] = {fg = "#eb6f92", bg = "#191724"},
["lualine_c_diff_removed_inactive"] = {fg = "#eb6f92", bg = "#191724"},
["lualine_c_diff_removed_insert"] = {fg = "#eb6f92", bg = "#191724"},
["lualine_c_diff_removed_normal"] = {fg = "#eb6f92", bg = "#191724"},
["lualine_c_diff_removed_replace"] = {fg = "#eb6f92", bg = "#191724"},
["lualine_c_diff_removed_terminal"] = {fg = "#eb6f92", bg = "#191724"},
["lualine_c_diff_removed_visual"] = {fg = "#eb6f92", bg = "#191724"},
["lualine_c_filename_command"] = {fg = "#c4a7e7", bg = "#191724", bold = true},
["lualine_c_filename_inactive"] = {fg = "#c4a7e7", bg = "#191724", bold = true},
["lualine_c_filename_insert"] = {fg = "#c4a7e7", bg = "#191724", bold = true},
["lualine_c_filename_normal"] = {fg = "#c4a7e7", bg = "#191724", bold = true},
["lualine_c_filename_replace"] = {fg = "#c4a7e7", bg = "#191724", bold = true},
["lualine_c_filename_terminal"] = {fg = "#c4a7e7", bg = "#191724", bold = true},
["lualine_c_filename_visual"] = {fg = "#c4a7e7", bg = "#191724", bold = true},
["lualine_c_inactive"] = {fg = "#e0def4", bg = "#191724"},
["lualine_c_normal"] = {fg = "#e0def4", bg = "#191724"},
["lualine_x_7_command"] = {fg = "#9ccfd8", bg = "#191724", bold = true},
["lualine_x_7_inactive"] = {fg = "#9ccfd8", bg = "#191724", bold = true},
["lualine_x_7_insert"] = {fg = "#9ccfd8", bg = "#191724", bold = true},
["lualine_x_7_normal"] = {fg = "#9ccfd8", bg = "#191724", bold = true},
["lualine_x_7_replace"] = {fg = "#9ccfd8", bg = "#191724", bold = true},
["lualine_x_7_terminal"] = {fg = "#9ccfd8", bg = "#191724", bold = true},
["lualine_x_7_visual"] = {fg = "#9ccfd8", bg = "#191724", bold = true},
["lualine_x_9_command"] = {fg = "#31748f", bg = "#191724", bold = true},
["lualine_x_9_inactive"] = {fg = "#31748f", bg = "#191724", bold = true},
["lualine_x_9_insert"] = {fg = "#31748f", bg = "#191724", bold = true},
["lualine_x_9_normal"] = {fg = "#31748f", bg = "#191724", bold = true},
["lualine_x_9_replace"] = {fg = "#31748f", bg = "#191724", bold = true},
["lualine_x_9_terminal"] = {fg = "#31748f", bg = "#191724", bold = true},
["lualine_x_9_visual"] = {fg = "#31748f", bg = "#191724", bold = true},
["lualine_x_diagnostics_error_command"] = {fg = "#ff0000", bg = "#191724"},
["lualine_x_diagnostics_error_inactive"] = {fg = "#ff0000", bg = "#191724"},
["lualine_x_diagnostics_error_insert"] = {fg = "#ff0000", bg = "#191724"},
["lualine_x_diagnostics_error_normal"] = {fg = "#ff0000", bg = "#191724"},
["lualine_x_diagnostics_error_replace"] = {fg = "#ff0000", bg = "#191724"},
["lualine_x_diagnostics_error_terminal"] = {fg = "#ff0000", bg = "#191724"},
["lualine_x_diagnostics_error_visual"] = {fg = "#ff0000", bg = "#191724"},
["lualine_x_diagnostics_hint_command"] = {fg = "#d3d3d3", bg = "#191724"},
["lualine_x_diagnostics_hint_inactive"] = {fg = "#d3d3d3", bg = "#191724"},
["lualine_x_diagnostics_hint_insert"] = {fg = "#d3d3d3", bg = "#191724"},
["lualine_x_diagnostics_hint_normal"] = {fg = "#d3d3d3", bg = "#191724"},
["lualine_x_diagnostics_hint_replace"] = {fg = "#d3d3d3", bg = "#191724"},
["lualine_x_diagnostics_hint_terminal"] = {fg = "#d3d3d3", bg = "#191724"},
["lualine_x_diagnostics_hint_visual"] = {fg = "#d3d3d3", bg = "#191724"},
["lualine_x_diagnostics_info_command"] = {fg = "#add8e6", bg = "#191724"},
["lualine_x_diagnostics_info_inactive"] = {fg = "#add8e6", bg = "#191724"},
["lualine_x_diagnostics_info_insert"] = {fg = "#add8e6", bg = "#191724"},
["lualine_x_diagnostics_info_normal"] = {fg = "#add8e6", bg = "#191724"},
["lualine_x_diagnostics_info_replace"] = {fg = "#add8e6", bg = "#191724"},
["lualine_x_diagnostics_info_terminal"] = {fg = "#add8e6", bg = "#191724"},
["lualine_x_diagnostics_info_visual"] = {fg = "#add8e6", bg = "#191724"},
["lualine_x_diagnostics_warn_command"] = {fg = "#ffa500", bg = "#191724"},
["lualine_x_diagnostics_warn_inactive"] = {fg = "#ffa500", bg = "#191724"},
["lualine_x_diagnostics_warn_insert"] = {fg = "#ffa500", bg = "#191724"},
["lualine_x_diagnostics_warn_normal"] = {fg = "#ffa500", bg = "#191724"},
["lualine_x_diagnostics_warn_replace"] = {fg = "#ffa500", bg = "#191724"},
["lualine_x_diagnostics_warn_terminal"] = {fg = "#ffa500", bg = "#191724"},
["lualine_x_diagnostics_warn_visual"] = {fg = "#ffa500", bg = "#191724"},
["lualine_x_fileformat_command"] = {fg = "#31748f", bg = "#191724", bold = true},
["lualine_x_fileformat_inactive"] = {fg = "#31748f", bg = "#191724", bold = true},
["lualine_x_fileformat_insert"] = {fg = "#31748f", bg = "#191724", bold = true},
["lualine_x_fileformat_normal"] = {fg = "#31748f", bg = "#191724", bold = true},
["lualine_x_fileformat_replace"] = {fg = "#31748f", bg = "#191724", bold = true},
["lualine_x_fileformat_terminal"] = {fg = "#31748f", bg = "#191724", bold = true},
["lualine_x_fileformat_visual"] = {fg = "#31748f", bg = "#191724", bold = true},
["lualine_x_location_command"] = {fg = "#e0def4", bg = "#191724", bold = true},
["lualine_x_location_inactive"] = {fg = "#e0def4", bg = "#191724", bold = true},
["lualine_x_location_insert"] = {fg = "#e0def4", bg = "#191724", bold = true},
["lualine_x_location_normal"] = {fg = "#e0def4", bg = "#191724", bold = true},
["lualine_x_location_replace"] = {fg = "#e0def4", bg = "#191724", bold = true},
["lualine_x_location_terminal"] = {fg = "#e0def4", bg = "#191724", bold = true},
["lualine_x_location_visual"] = {fg = "#e0def4", bg = "#191724", bold = true},
["lualine_x_progress_command"] = {fg = "#e0def4", bg = "#191724", bold = true},
["lualine_x_progress_inactive"] = {fg = "#e0def4", bg = "#191724", bold = true},
["lualine_x_progress_insert"] = {fg = "#e0def4", bg = "#191724", bold = true},
["lualine_x_progress_normal"] = {fg = "#e0def4", bg = "#191724", bold = true},
["lualine_x_progress_replace"] = {fg = "#e0def4", bg = "#191724", bold = true},
["lualine_x_progress_terminal"] = {fg = "#e0def4", bg = "#191724", bold = true},
["lualine_x_progress_visual"] = {fg = "#e0def4", bg = "#191724", bold = true},
-- PATCH_CLOSE
-- content here will not be touched
}

-- colorschemes generally want to do this
vim.cmd("highlight clear")
vim.cmd("set t_Co=256")
vim.cmd("let g:colors_name='my_theme'")

-- apply highlight groups
for group, attrs in pairs(colors) do
  vim.api.nvim_set_hl(0, group, attrs)
end
